## Tensors
A tensor is a fundamental data structure for neural network. A tensor is generalization of matrix. A 1-dimensional tensor is vector, a two-dimensional tensor is matrix and n-dimensional array is tensor. 

In [1]:
#import PyTorch

In [3]:
import torch

In [4]:
def activation(x):
    """ Sigmoid activation function
        Arguements
        ----------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [5]:
torch.manual_seed(7) #set the random seed so thigns are predictable

features = torch.randn(1, 5) #random nomral variables with five elements

weights = torch.randn_like(features) #true weights for our data. Same shape as features

bias = torch.randn(1,1) #A single value for bias

In [6]:
# Calculate the output for this neural network with input features features, weights, and bias. We will use matrix multiplication
# between features and weights and add bias element to it. The output is then passed on to activiation fucntion to generate the final result

y = activation(torch.sum(features * weights)+bias) #here we do elements by element multiplicatio and bias
print(y)

# alternatively we could use sum function on tensor
y = activation((features*weights).sum() +bias)
print(y)


tensor([[0.1595]])
tensor([[0.1595]])


In [7]:
#use matrix multiplication using torch.mm() for high performance
# We are goign to resize the weights based on teh shape of features. For matrix multiplifcation we want 1 x 5 * 5 x 1. 
# we use view on tensor and specify desired shape to get a new tensor with same data element. The view takes (row, column)
# this is simply saying activation(torch.mm(features, weigths.view(5,1))+bias). 


In [8]:
y = activation(torch.mm(features, weights.view(features.size()[1], features.size()[0])) +bias)
print(y)

tensor([[0.1595]])


## Multilayer Network
We have features and weights.The multiplicaiot of weigth and features makes a hidden units. 

             O           #One output unit 

         h1      h2      #Two hidden units
         
    x1       x2      x3  #Three inpu features
 
Our problem is expressed as below:
y = xi*wi + b

                                                                 [w11 w12]
                                                                 [w11 w12]
     The hidden lay h is calcualed as h=[h1,h2] = [x1,x2,x3..xn].[:    : ]
                                                                 [:    : ]
                                                                 [wn1 wn2]
                                                                


In [17]:


### Generate some data
#set the random seed so we are getting the same set of data each time
torch.manual_seed(7)

#Features are three random normal variables
features = torch.rand((1,3))

#Define the size of each layer in the network
n_input = features.shape[1] #Number of input units, this must match the number of input features. our input features is 1 x 3 matrix and thus we have 3 features in this case
n_hidden = 2 #Number of hidden units
n_output = 1 #Number of outputs


#weigths for input to hidden layer
w1 = torch.rand(n_input, n_hidden)

#Weights for hidden layer to output layer
w2 = torch.randn(n_hidden, n_output)

#Bias
B1 = torch.randn((1,n_hidden))
B1 = torch.randn((1,n_output))


#printing input data
print("Features:")
print(features)

print("Weights of features:")
print(w1)

print("Weights of hidden units:")
print(w2)

h = activation(torch.mm(features, w1)+B1)
output = activation(torch.mm(h, w2)+B1)


print("Hidden Units:")
print(h)
print("Output:")
print(output)




Features:
tensor([[0.5349, 0.1988, 0.6592]])
Weights of features:
tensor([[0.6569, 0.2328],
        [0.4251, 0.2071],
        [0.6297, 0.3653]])
Weights of hidden units:
tensor([[ 0.3775],
        [-0.9509]])
Hidden Units:
tensor([[0.2959, 0.2123]])
Output    tensor([[0.1409]])
tensor([[0.1409]])


In [18]:
## Numpy to Torch and back


In [31]:
import numpy as np               #import numpy
np.random.seed(7)
a = np.random.rand(4,3)          #a numpy array
print(a)
b = torch.from_numpy(a)          #creata a tensor from numpy array\
print(b)                         #note than tensor always have dtype which ndarray does not


[[0.07630829 0.77991879 0.43840923]
 [0.72346518 0.97798951 0.53849587]
 [0.50112046 0.07205113 0.26843898]
 [0.4998825  0.67923    0.80373904]]
tensor([[0.0763, 0.7799, 0.4384],
        [0.7235, 0.9780, 0.5385],
        [0.5011, 0.0721, 0.2684],
        [0.4999, 0.6792, 0.8037]], dtype=torch.float64)


In [30]:
b.numpy()                        #gives back numpy array. Memory is shared between numpy and torch
b.mul_(2)                        #inplace operation of multipying by 2 on tensor, changes the value of numpy array
print(a)                        #Notice the changed values
print(b)


[[0.15261658 1.55983758 0.87681846]
 [1.44693036 1.95597902 1.07699174]
 [1.00224093 0.14410227 0.53687796]
 [0.999765   1.35845999 1.60747807]]
tensor([[0.1526, 1.5598, 0.8768],
        [1.4469, 1.9560, 1.0770],
        [1.0022, 0.1441, 0.5369],
        [0.9998, 1.3585, 1.6075]], dtype=torch.float64)


## Neural Networks in PyTorch

In [41]:
from torchvision import datasets, transforms

#define a transform to normalize the data
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((.5, .5, .5), (.5, .5, .5)),])

#Downloa dn load the training data
trainset = datasets.MNIST('MNIST_data/', download=True, train=True, transform = transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)
